export { default as SidebarLeft } from './SidebartLeft'
export { default as SidebarRight } from './SidebartRight'
export { default as Header } from './Header'
export { default as Search } from './Search'
export { default as Slider } from './Slider'
export { default as Player } from './Player'